### PR TITLE
Various protocol improvements

### PR DESCRIPTION
**Pull request by NumberFour8**
Implement version 0.3.0 of the protocol.

- add dual counters (per request/response)
- add timestamp support

### CODE REVIEW

**Review by tolbrino — APPROVED** [review]
Some inline documentation for each function would be nice.

**Comment by NumberFour8** [comment]
> Some inline documentation for each function would be nice.

Added inline documentation and updated specs.

**Review by robertkiel — APPROVED** [review]
lgtm :+1:

**Review by nionis — APPROVED** [review]
thanks

**Pull request merged**
